version: "3.3"
services:
  buq:
    image: openlmis/buq
    links:
      - db
      - log
    ports:
      - "8080"
    env_file: .env
  db:
    image: openlmis/postgres:12-debezium
    env_file: .env
  log:
    image: openlmis/rsyslog:3
    volumes:
      - '../logs/buq:/var/log'
